### ISSUE TITLE
Change maintainer :D

### ISSUE THREAD

**Issue by ynohat** [derDieDasJojo/parse-cloudcode#1]
Hello,

I just got an email from microbadger.com asking me to add their badge to my docker repository ... derDieDasJojo/parse-cloudcode.

On closer examination, it seems you must have bootstrapped your Dockerfile off of one I wrote lately, because I recognise the comments and content of the Dockerfile, but you also left me as the maintainer, verbatim.

So I'm flattered, but I think you should take the credit, really ;)

Cheers,

**Comment by derDieDasJojo** [comment]
ups. I changed it.
thanks for the template and take the flattered credit :)
